name: Build and Norminette checks

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed to create releases

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install norminette
      run: |
        python -m pip install --upgrade pip
        pip install norminette

    - name: Run norminette
      run: norminette

    - name: Build project
      run: make re

    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: codexion
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
